[Sun May 08 2016 19:51:23 GMT+0800 (中国标准时间)]/
Error: An error for test purposes
    at Object.<anonymous> (D:\JavaScript学习\learning-of-nodejs\project\microblog\routes\index.js:7:9)
    at nextMiddleware (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\router.js:175:25)
    at param (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\router.js:183:17)
    at pass (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\router.js:191:11)
    at Object.router (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\router.js:197:7)
    at next (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\http.js:204:15)
    at next (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\session.js:322:9)
    at D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\express\node_modules\connect\lib\middleware\session.js:341:9
    at D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\connect-mongo\lib\connect-mongo.js:305:11
    at handleCallback (D:\JavaScript学习\learning-of-nodejs\project\microblog\node_modules\connect-mongo\node_modules\mongodb\lib\utils.js:96:12)
